speech_recognition:
  model_size: "base.en"  # The Faster-Whisper model size to use (see hugging face for more options).
  allow_downloads: false  # Set to true to allow downloading of models other than the default. Disable when done.
  device: "auto"  # cpu, gpu, or auto. Default = "auto".
  cpu_threads: 8
  num_workers: 8